version: '3.8'
services:
    chrome:
        image: selenium/standalone-chrome
        restart: always
        ports: 
          - 4444:4444
        networks:
         front:
            ipv4_address: 172.16.238.5
    net-worker:
        build: .
        depends_on: 
          - chrome
        networks:
         front:
            ipv4_address: 172.16.238.10 
          
networks:
    front:
        driver: bridge
        ipam:
            config:
             - subnet: 172.16.238.0/24